import fs from "node:fs"
import path from "node:path"

const GENERATED_HEADER = "/* AUTO-GENERATED by `wse sync` — do not edit. */"

/**
 * Next.js file conventions that must exist inside the app directory itself.
 * Everything else in a package's app tree is a helper module and needs no stub.
 */
const ROUTE_FILE_RE =
  /^(page|layout|route|error|global-error|loading|not-found|template|default|forbidden|unauthorized)\.(ts|tsx)$/
const METADATA_FILE_RE = /^(robots|sitemap|manifest)\.(ts|tsx)$/

function isRouteFile(relPath) {
  const base = path.basename(relPath)
  if (ROUTE_FILE_RE.test(base)) return true
  // metadata routes are only conventions at the app root
  if (!relPath.includes(path.sep) && METADATA_FILE_RE.test(base)) return true
  return false
}

function walk(dir, base = dir, out = []) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name)
    if (entry.isDirectory()) walk(full, base, out)
    else out.push(path.relative(base, full))
  }
  return out
}

function stubContents(specifier, relPath, { injectGlobalsCss }) {
  const base = path.basename(relPath)
  const noExt = relPath.replace(/\.(ts|tsx)$/, "")
  const target = `${specifier}/${noExt.split(path.sep).join("/")}`
  const lines = []
  // Next requires the error files themselves to be client components.
  if (base.startsWith("error.") || base.startsWith("global-error.")) {
    lines.push(`"use client"`)
  }
  lines.push(GENERATED_HEADER)
  if (injectGlobalsCss) lines.push(`import "./globals.css"`)
  lines.push(`export * from "${target}"`)
  // route.ts handlers export named methods only; everything else has a default export.
  if (!base.startsWith("route.")) {
    lines.push(`export { default } from "${target}"`)
  }
  return lines.join("\n") + "\n"
}

export function syncApp(appDir) {
  const configPath = path.join(appDir, "wse.config.json")
  if (!fs.existsSync(configPath)) {
    throw new Error(`No wse.config.json found in ${appDir}`)
  }
  const config = JSON.parse(fs.readFileSync(configPath, "utf8"))
  const appRoot = path.join(appDir, "src", "app")
  fs.mkdirSync(appRoot, { recursive: true })

  const wanted = new Map()
  for (const source of config.routeSources ?? []) {
    const sourceDir = path.resolve(appDir, source.dir)
    if (!fs.existsSync(sourceDir)) {
      throw new Error(`Route source dir not found: ${sourceDir}`)
    }
    const exclude = (source.exclude ?? []).map((p) => p.split("/").join(path.sep))
    for (const rel of walk(sourceDir)) {
      if (!isRouteFile(rel)) continue
      if (exclude.some((ex) => rel === ex || rel.startsWith(ex + path.sep))) continue
      wanted.set(rel, {
        specifier: source.specifier,
        injectGlobalsCss: rel === "layout.tsx" && source.injectGlobalsCss === true,
      })
    }
  }

  let written = 0
  let skipped = 0
  for (const [rel, meta] of wanted) {
    const dest = path.join(appRoot, rel)
    if (fs.existsSync(dest)) {
      const current = fs.readFileSync(dest, "utf8")
      if (!current.includes(GENERATED_HEADER)) {
        skipped++ // app-local override wins
        continue
      }
    }
    fs.mkdirSync(path.dirname(dest), { recursive: true })
    const contents = stubContents(meta.specifier, rel, meta)
    if (!fs.existsSync(dest) || fs.readFileSync(dest, "utf8") !== contents) {
      fs.writeFileSync(dest, contents)
      written++
    }
  }

  // remove stale generated stubs that no longer map to a source route
  let removed = 0
  for (const rel of walk(appRoot)) {
    const dest = path.join(appRoot, rel)
    const contents = fs.readFileSync(dest, "utf8")
    if (!contents.includes(GENERATED_HEADER)) continue
    if (!wanted.has(rel)) {
      fs.unlinkSync(dest)
      removed++
    }
  }

  return { written, skipped, removed, total: wanted.size }
}

export async function runSync(args) {
  const appFlag = args.indexOf("--app")
  const appDir = path.resolve(appFlag >= 0 ? args[appFlag + 1] : process.cwd())
  const result = syncApp(appDir)
  console.log(
    `wse sync: ${result.total} routes — wrote ${result.written}, kept ${result.skipped} local overrides, removed ${result.removed} stale stubs`
  )
}
